version: '3'

volumes:
  dev_soflow_data: {}
  dev_soflow_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: soflow_dev_django
    depends_on:
      - redis
    env_file:
      - ./.envs/.production/.django
    environment:
      DJANGO_SETTINGS_MODULE: saleor.settings
      GOOGLE_SECRETS_NAME: soflow-api-dev-env
    ports:
      - "8000:8000"
    command: /start

  redis:
    image: redis:6
    container_name: redis

  celeryworker:
    <<: *django
    image: soflow_dev_celeryworker
    container_name: celeryworker
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: soflow_dev_celerybeat
    container_name: celerybeat
    ports: []
    command: /start-celerybeat
