#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset

python /app/manage.py migrate
python /app/manage.py collectstatic --noinput
/usr/local/bin/gunicorn saleor.asgi:application --bind 0.0.0.0:8000 --chdir=/app --workers=10 -k saleor.asgi.gunicorn_worker.UvicornWorker
