# name: Deploy to Main

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     name: Deploy to Main
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up SSH
#         uses: webfactory/ssh-agent@v0.5.3
#         with:
#           ssh-private-key: aws

#       - name: Deploy to Main
#         run: ssh -o StrictHostKeyChecking=no salvadev404@35.202.34.209 "sh /var/www/saleor-backend/deployment/deploy.sh"